@startuml

!theme carbon-gray

!define model << (M,LightSalmon) >>
!define schema << (S,LightBlue) >>


title Data Models

class quantityPricing schema {
  + basePpu: Number
  + retail: Number
  + bulk_factors: [{quantity,costModifier}]
  == Virtual ==
  + getBulkPrices: [{quantity,costModifier}]
  + getSuggestedRetail: Number
}
class OptionGroups schema {
  + groupName String
  + refs: [String]
  + options: [{String,Number}]
}
class Item model {
  + category: String
  + skuPrefix: String
  + type: String
  + name: String
  + description: String
  + stock: Number
  + madeIn: String
  + manufacturer: Manufacturer[1]
  + quantityPricing: quantityPricing
  + optionGroups: OptionGroups
  + timeCreated: Date
  + timeUpdated: Date
  == Virtual ==
  + url: String
}


class Contact schema {
  + website: String
  + location: String
  + email: String
  + Phone: String
}
class Manufacturer model {
  + name: String
  + description: String
  + contact: Contact
  + timeCreated: Date
  + timeUpdated: Date
  == Virtual ==
  + url: String
}
class SkuCounter model {
  + prefix: String
  + sku: Number
  --
  + nextSku(): String
  == Virtual ==
  current: String
}
Contact --* Manufacturer
Item  -- "1" Manufacturer
quantityPricing --* Item
OptionGroups --* Item
Item .> SkuCounter : uses

@enduml